# Generated by Django 4.0.3 on 2022-04-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=50, verbose_name='имя автора'),
        ),
    ]
